apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fintrack

resources:
  # 1. Namespace first
  - namespace.yaml

  # 2. Secrets
  - secrets.yaml

  # 3. Infrastructure
  - infrastructure/postgres.yaml
  - infrastructure/rabbitmq.yaml
  - infrastructure/nexus.yaml

  # 4. Application services
  - apps/fintrack-api.yaml
  - apps/transaction-aggregator.yaml

  # 5. Ingress
  - ingress.yaml