apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-pvc
  namespace: fintrack
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus
  namespace: fintrack
  labels:
    app: nexus
    app.kubernetes.io/part-of: fintrack-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus
  template:
    metadata:
      labels:
        app: nexus
    spec:
      containers:
        - name: nexus
          image: sonatype/nexus3:3.68.0
          ports:
            - containerPort: 8081
          env:
            - name: INSTALL4J_ADD_VM_PARAMS
              value: "-Xms256m -Xmx512m -XX:MaxDirectMemorySize=512m"
          volumeMounts:
            - name: nexus-data
              mountPath: /nexus-data
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
          readinessProbe:
            httpGet:
              path: /service/rest/v1/status
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 15
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /service/rest/v1/status
              port: 8081
            initialDelaySeconds: 120
            periodSeconds: 30
            timeoutSeconds: 5
      volumes:
        - name: nexus-data
          persistentVolumeClaim:
            claimName: nexus-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: nexus
  namespace: fintrack
  labels:
    app: nexus
spec:
  selector:
    app: nexus
  ports:
    - name: http
      port: 8081
      targetPort: 8081
