apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-scripts
  namespace: fintrack
data:
  init-databases.sh: |
    #!/bin/bash
    set -e
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
      CREATE DATABASE fintrack_api;
      CREATE DATABASE fintrack_agg;
      GRANT ALL PRIVILEGES ON DATABASE fintrack_api TO $POSTGRES_USER;
      GRANT ALL PRIVILEGES ON DATABASE fintrack_agg TO $POSTGRES_USER;
    EOSQL

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: fintrack
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: fintrack
  labels:
    app: postgres
    app.kubernetes.io/part-of: fintrack-platform
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: fintrack-secrets
                  key: db-api-username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fintrack-secrets
                  key: db-admin-password
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
            - name: init-scripts
              mountPath: /docker-entrypoint-initdb.d
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "fintrack"]
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "fintrack"]
            initialDelaySeconds: 30
            periodSeconds: 10
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc
        - name: init-scripts
          configMap:
            name: postgres-init-scripts
            defaultMode: 0755

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: fintrack
  labels:
    app: postgres
spec:
  selector:
    app: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  clusterIP: None  # headless for StatefulSet
